Handle already memoized strings and BINGET
glencoesoftware/omero-ms-core pull request #27
Opened 2023-06-21 12:43 UTC by chris-allan

Under certain conditions a string may have already been "memoized" during the pickling process.  If this is the case, the value during opcode sequence unwinding is handled by reference (the offset within the "memo") rather than by value.

The implementation here is a shortcut as we do not care about decoding the entire Django session but rather just the OMERO.web Connector.

See:
 * https://github.com/python/cpython/blob/3.10/Lib/pickletools.py

2023-06-21 12:49 UTC, chris-allan commented
The symbolic disassembly of the new pickle (created using `pickletools.dis`) is as follows:

```
    0: \x80 PROTO      4
    2: \x95 FRAME      2161
   11: }    EMPTY_DICT
   12: \x94 MEMOIZE    (as 0)
   13: (    MARK
   14: \x8c     SHORT_BINUNICODE 'callback'
   24: \x94     MEMOIZE    (as 1)
   25: }        EMPTY_DICT
   26: \x94     MEMOIZE    (as 2)
   27: (        MARK
   28: \x8c         SHORT_BINUNICODE 'ProcessCallback/da39c719-110b-4777-bf48-a19e81f56d50 -t -e 1.1:tcp -h 10.0.13.5 -p 43649 -t 60000'
  127: \x94         MEMOIZE    (as 3)
  128: }            EMPTY_DICT
  129: \x94         MEMOIZE    (as 4)
  130: (            MARK
  131: \x8c             SHORT_BINUNICODE 'job_type'
  141: \x94             MEMOIZE    (as 5)
  142: \x8c             SHORT_BINUNICODE 'script'
  150: \x94             MEMOIZE    (as 6)
  151: \x8c             SHORT_BINUNICODE 'job_name'
  161: \x94             MEMOIZE    (as 7)
  162: \x8c             SHORT_BINUNICODE 'Export Capabilities'
  183: \x94             MEMOIZE    (as 8)
  184: \x8c             SHORT_BINUNICODE 'start_time'
  196: \x94             MEMOIZE    (as 9)
  197: \x8c             SHORT_BINUNICODE 'datetime'
  207: \x94             MEMOIZE    (as 10)
  208: \x8c             SHORT_BINUNICODE 'datetime'
  218: \x94             MEMOIZE    (as 11)
  219: \x93             STACK_GLOBAL
  220: \x94             MEMOIZE    (as 12)
  221: C                SHORT_BINBYTES b'\x07\xe7\x06\x13\x14!\x12\x02)\xe2'
  233: \x94             MEMOIZE    (as 13)
  234: \x85             TUPLE1
  235: \x94             MEMOIZE    (as 14)
  236: R                REDUCE
  237: \x94             MEMOIZE    (as 15)
  238: \x8c             SHORT_BINUNICODE 'status'
  246: \x94             MEMOIZE    (as 16)
  247: \x8c             SHORT_BINUNICODE 'finished'
  257: \x94             MEMOIZE    (as 17)
  258: \x8c             SHORT_BINUNICODE 'results'
  267: \x94             MEMOIZE    (as 18)
  268: }                EMPTY_DICT
  269: \x94             MEMOIZE    (as 19)
  270: \x8c             SHORT_BINUNICODE 'Options'
  279: \x94             MEMOIZE    (as 20)
  280: \x8c             SHORT_BINUNICODE 'TIFF PNG'
  290: \x94             MEMOIZE    (as 21)
  291: s                SETITEM
  292: u                SETITEMS   (MARK at 130)
  293: \x8c         SHORT_BINUNICODE '5bab6cda-2d78-415e-a080-958586801696/IHandle225c0aef-9c45-447a-a661-3f3cdb5da693 -t -e 1.1:tcp -h 10.0.13.5 -p 43649 -t 60000'
  420: \x94         MEMOIZE    (as 22)
  421: }            EMPTY_DICT
  422: \x94         MEMOIZE    (as 23)
  423: (            MARK
  424: \x8c             SHORT_BINUNICODE 'job_type'
  434: \x94             MEMOIZE    (as 24)
  435: \x8c             SHORT_BINUNICODE 'delete'
  443: \x94             MEMOIZE    (as 25)
  444: \x8c             SHORT_BINUNICODE 'start_time'
  456: \x94             MEMOIZE    (as 26)
  457: h                BINGET     12
  459: C                SHORT_BINBYTES b'\x07\xe7\x06\x13\x15\x04\x04\x0bQs'
  471: \x94             MEMOIZE    (as 27)
  472: \x85             TUPLE1
  473: \x94             MEMOIZE    (as 28)
  474: R                REDUCE
  475: \x94             MEMOIZE    (as 29)
  476: \x8c             SHORT_BINUNICODE 'status'
  484: \x94             MEMOIZE    (as 30)
  485: \x8c             SHORT_BINUNICODE 'finished'
  495: \x94             MEMOIZE    (as 31)
  496: \x8c             SHORT_BINUNICODE 'error'
  503: \x94             MEMOIZE    (as 32)
  504: K                BININT1    0
  506: \x8c             SHORT_BINUNICODE 'dreport'
  515: \x94             MEMOIZE    (as 33)
  516: N                NONE
  517: \x8c             SHORT_BINUNICODE 'dtype'
  524: \x94             MEMOIZE    (as 34)
  525: \x8c             SHORT_BINUNICODE 'Dataset'
  534: \x94             MEMOIZE    (as 35)
  535: \x8c             SHORT_BINUNICODE 'delmany'
  544: \x94             MEMOIZE    (as 36)
  545: \x89             NEWFALSE
  546: \x8c             SHORT_BINUNICODE 'did'
  551: \x94             MEMOIZE    (as 37)
  552: \x8c             SHORT_BINUNICODE '1'
  555: \x94             MEMOIZE    (as 38)
  556: u                SETITEMS   (MARK at 423)
  557: \x8c         SHORT_BINUNICODE '5bab6cda-2d78-415e-a080-958586801696/IHandle14ee4bc6-b003-4669-80ca-d2102fd5515f -t -e 1.1:tcp -h 10.0.13.5 -p 43649 -t 60000'
  684: \x94         MEMOIZE    (as 39)
  685: }            EMPTY_DICT
  686: \x94         MEMOIZE    (as 40)
  687: (            MARK
  688: \x8c             SHORT_BINUNICODE 'job_type'
  698: \x94             MEMOIZE    (as 41)
  699: \x8c             SHORT_BINUNICODE 'delete'
  707: \x94             MEMOIZE    (as 42)
  708: \x8c             SHORT_BINUNICODE 'start_time'
  720: \x94             MEMOIZE    (as 43)
  721: h                BINGET     12
  723: C                SHORT_BINBYTES b'\x07\xe7\x06\x13\x15\x04\t\x07\x9c8'
  735: \x94             MEMOIZE    (as 44)
  736: \x85             TUPLE1
  737: \x94             MEMOIZE    (as 45)
  738: R                REDUCE
  739: \x94             MEMOIZE    (as 46)
  740: \x8c             SHORT_BINUNICODE 'status'
  748: \x94             MEMOIZE    (as 47)
  749: \x8c             SHORT_BINUNICODE 'finished'
  759: \x94             MEMOIZE    (as 48)
  760: \x8c             SHORT_BINUNICODE 'error'
  767: \x94             MEMOIZE    (as 49)
  768: K                BININT1    0
  770: \x8c             SHORT_BINUNICODE 'dreport'
  779: \x94             MEMOIZE    (as 50)
  780: N                NONE
  781: \x8c             SHORT_BINUNICODE 'dtype'
  788: \x94             MEMOIZE    (as 51)
  789: \x8c             SHORT_BINUNICODE 'Dataset'
  798: \x94             MEMOIZE    (as 52)
  799: \x8c             SHORT_BINUNICODE 'delmany'
  808: \x94             MEMOIZE    (as 53)
  809: \x89             NEWFALSE
  810: \x8c             SHORT_BINUNICODE 'did'
  815: \x94             MEMOIZE    (as 54)
  816: \x8c             SHORT_BINUNICODE '2'
  819: \x94             MEMOIZE    (as 55)
  820: u                SETITEMS   (MARK at 687)
  821: \x8c         SHORT_BINUNICODE '5bab6cda-2d78-415e-a080-958586801696/IHandle873a5965-1576-425c-8854-b06dd4991d04 -t -e 1.1:tcp -h 10.0.13.5 -p 43649 -t 60000'
  948: \x94         MEMOIZE    (as 56)
  949: }            EMPTY_DICT
  950: \x94         MEMOIZE    (as 57)
  951: (            MARK
  952: \x8c             SHORT_BINUNICODE 'job_type'
  962: \x94             MEMOIZE    (as 58)
  963: \x8c             SHORT_BINUNICODE 'delete'
  971: \x94             MEMOIZE    (as 59)
  972: \x8c             SHORT_BINUNICODE 'start_time'
  984: \x94             MEMOIZE    (as 60)
  985: h                BINGET     12
  987: C                SHORT_BINBYTES b'\x07\xe7\x06\x13\x15\x04\x0f\x03\xcc\xfc'
  999: \x94             MEMOIZE    (as 61)
 1000: \x85             TUPLE1
 1001: \x94             MEMOIZE    (as 62)
 1002: R                REDUCE
 1003: \x94             MEMOIZE    (as 63)
 1004: \x8c             SHORT_BINUNICODE 'status'
 1012: \x94             MEMOIZE    (as 64)
 1013: \x8c             SHORT_BINUNICODE 'finished'
 1023: \x94             MEMOIZE    (as 65)
 1024: \x8c             SHORT_BINUNICODE 'error'
 1031: \x94             MEMOIZE    (as 66)
 1032: K                BININT1    0
 1034: \x8c             SHORT_BINUNICODE 'dreport'
 1043: \x94             MEMOIZE    (as 67)
 1044: N                NONE
 1045: \x8c             SHORT_BINUNICODE 'dtype'
 1052: \x94             MEMOIZE    (as 68)
 1053: \x8c             SHORT_BINUNICODE 'Dataset'
 1062: \x94             MEMOIZE    (as 69)
 1063: \x8c             SHORT_BINUNICODE 'delmany'
 1072: \x94             MEMOIZE    (as 70)
 1073: \x89             NEWFALSE
 1074: \x8c             SHORT_BINUNICODE 'did'
 1079: \x94             MEMOIZE    (as 71)
 1080: \x8c             SHORT_BINUNICODE '3'
 1083: \x94             MEMOIZE    (as 72)
 1084: u                SETITEMS   (MARK at 951)
 1085: u            SETITEMS   (MARK at 27)
 1086: \x8c     SHORT_BINUNICODE 'shares' [...]

2023-06-22 20:14 UTC, kkoz requested changes

2023-06-22 20:22 UTC, chris-allan commented on src/main/java/com/glencoesoftware/omero/ms/core/PickledSessionConnector.java
> +                memoOffset++;
The offsets stored are relative to every memoized value not just the strings we care about so this will not work.

2023-06-26 12:01 UTC, sbesson approved these changes
Code changes look good and in agreement with the internal pickle format and its caching mechanism.

Confirmed that unpickling the base64 encoded session returns the values expected in the unit tests.
Also deployed a modified version of the thumbnail/image-region micro-services with these changes and the session connection logic seems to be working fine.

I'll wait for @kkoz  to add his review but from my perspective, this is fine to integrate and get released as we'll need `omero-ms-{thumbnail,pixel-buffer,image-region}` to all consume the latest version. Are these repositories following semver in which case the next release should likely be `0.7.0` as per the backwards-incompatible changes made to the public methods of `PickledSessionConnector`?

2023-06-29 14:47 UTC, kkoz approved these changes

2023-06-29 14:57 UTC, chris-allan commented
0.7.0 release makes sense, @sbesson. I can't imagine anyone else is consuming omero-ms-core but it's good hygiene nonetheless.

2023-06-29 14:57 UTC, merged