Log session when session unpickling fails
glencoesoftware/omero-ms-core pull request #34
Opened 2024-06-10 19:56 UTC by kkoz

Previously, to debug an "unpickling" error, we had to dig through Redis to find the session which had created the error. With these changes, exceptions thrown during the unpickling process are caught and the failing session is logged. We also added some logic to give more useful errors in the case where a `BINGET` requests a memoized item which is not present in the `memo` object.

2024-06-11 10:49 UTC, chris-allan requested changes

2024-06-11 10:49 UTC, chris-allan commented on src/main/java/com/glencoesoftware/omero/ms/core/PickledSessionConnector.java
> +                            log.warn("Unexpected field name in connector: "
Use parameterized logging:

 * https://www.slf4j.org/faq.html#logging_performance

2024-06-11 10:49 UTC, chris-allan commented on src/main/java/com/glencoesoftware/omero/ms/core/PickledSessionConnector.java
> +                    log.error("Pickled Session: " + b64Session);
As above.

Also, I would assume we would rather want to surround the `init()` in the constructor with a try block and log this at ERROR level if an exception is thrown there, no?

2024-06-11 10:49 UTC, chris-allan commented on src/test/java/com/glencoesoftware/omero/ms/core/PickledSessionConnectorTest.java
> +        IConnector v = new PickledSessionConnector(
Do you want to check the values have been decoded correctly?

2024-06-11 10:49 UTC, chris-allan commented on src/test/java/com/glencoesoftware/omero/ms/core/PickledSessionConnectorTest.java
> +        IConnector v = new PickledSessionConnector(
As above.

2025-02-12 11:17 UTC, sbesson approved these changes
@chris-allan could you check the last commits address your requested changes? As we will likely cut a new patch release of `omero-ms-core`, this might be a good opportunity to include these changes so that we have additional logging next time the session unpickling fails.

2025-02-13 10:20 UTC, merged